"""add manual_url field to categories

Revision ID: a92554233d96
Revises: 1fbbc18438bc
Create Date: 2025-08-05 10:06:09.484554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92554233d96'
down_revision: Union[str, None] = '1fbbc18438bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('manual_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'manual_url')
    # ### end Alembic commands ###
